name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag naomilev1/hello-node:node
    - name: run & test Container
      run: docker run -itd --name node-hello -p 3000:3000 naomilev1/hello-node:node
    - run: sleep 5 && curl localhost:3000
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: docker push naomilev1/hello-node:node
